## 1. O pipeline é ativado quando houver push na branch main
name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Só ativa na branch main

jobs:
  CI:  # Job de Integração Contínua
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do código-fonte do repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # SonarQube Cloud Scan
      # Faz o scan do código-fonte usando o SonarCloud
      # O token e as credenciais do SonarCloud devem ser armazenados como secrets no repositório
      # O projeto deve estar previamente configurado no SonarCloud
      # O SonarCloud é uma ferramenta de análise de código que ajuda a identificar problemas de qualidade e segurança  

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: ./src
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Realiza o login no Docker Hub com credenciais armazenadas como secrets
      - name: Set up Docker
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.SECRET_RACO1 }}
          password: ${{ secrets.SECRET_RACO }}

      # Constrói a imagem Docker e faz o push para o Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            raco21/kube-news:v${{ github.run_number }}

      # Executa o Trivy para fazer o scan de vulnerabilidades na imagem Docker recém-criada
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: 'image'
          image-ref: 'raco21/kube-news:v${{ github.run_number }}'
          format: table
          output: 'trivy-docker-results.txt'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          hide-progress: true

      # Publica o relatório do Trivy no sumário da execução do GitHub Actions (se couber no limite de tamanho)
      - name: Publicar o Trivy no Sumario
        run: |
          if [[ -s trivy-docker-results.txt ]]; then
            {
              echo "### Relatorio de Vulnerabilidades (Imagem Docker)"
              echo "<details><summary>Expandir</summary>"
              echo ""
              cat trivy-docker-results.txt
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi

      # Salva o relatório do Trivy como artifact para download posterior (mesmo se for muito grande pro summary)
      - name: Upload Trivy Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-docker-results.txt    

      # Cria um novo release do projeto no GitHub, usando tag e nome (deve ser dinâmico na prática)
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v9.9.2.0   # Substitua por uma versão dinâmica, se desejar
          release_name: Release v9.9.2.0
          body: |
            Esta é a versão 9.9.2.0 da aplicação.
            - Lista de mudanças relevantes no release.
          draft: false
          prerelease: false

      # Envia um email ao DevOps se algo falhar nesse job
      - name: Notify Failure
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          subject: "Approval Job Failed - ${{ github.repository }}"
          body: "O job de aprovação falhou para o repositório ${{ github.repository }}. Confira o workflow para mais detalhes."
          to: ${{ secrets.DEVELOPER_EMAIL }}    

  # 2. Deploy só será executado se o CI passar com sucesso
  CD:
    runs-on: ubuntu-latest
    needs:
      - CI  # Só executa se o job CI for bem sucedido
    environment: 
      name: production # Mude para o nome do ambiente real de destino, se desejar
    steps:
      # Checkout do código (necessário para arquivos de manifesto ou scripts)
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Seta o contexto do cluster Kubernetes (com o kubeconfig passado via secret)
      - name: Set Kubernetes Context
        uses: Azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      # Faz o deploy da nova versão da imagem Docker no cluster Kubernetes usando o manifesto informado
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9     
        with:
          images: raco21/kube-news:v${{ github.run_number }}
          manifests: |
            k8s/deployment.yaml

      # Recupera e exibe o IP público da aplicação a partir do serviço do Kubernetes
      - name: Get Application URL
        run: |
          APP_IP=$(kubectl get svc kubenews -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "Application is available at http://${APP_IP}"

      # Envia um email para o DevOps informando o êxito do deploy
      - name: Notify on CI Approval
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          subject: "CI Job Approved - ${{ github.repository }}"
          body: |
            O job CI foi aprovado para o repositório ${{ github.repository }}.
            A aplicação está disponível
          to: ${{ secrets.DEVELOPER_EMAIL }}